openapi: 3.0.0
info:
  title: eShop
  version: '0.1'
  contact:
    name: Zerai Teclai
    email: teclaizerai@googlemail.com
    url: 'https://eshop-demo.example.com'
  license:
    name: MIT
    url: 'https://github.com/zerai/eshop/blob/main/LICENSE'
  description: An eShop demo application

servers:
  - url: 'http://localhost:80'
    description: Local

tags:
  - name: user
    description: Operations over users
  - name: catalog
    description: Operations over catalog items

paths:
  '/api/users':
    get:
      summary: Get User List
      responses:
        '200':
          description: Users Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      operationId: get-users-list
      description: Retrieve the information of users.
      tags:
        - user

  '/api/catalog/items/{id}':
    get:
      tags:
        - catalog
      summary: Get Catalog Item
      description: Retrieve the information of catalog item.
      operationId: get-catalog-item-by-id
      parameters:
        - name: id
          in: path
          description: catalog item identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Catalog Items Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogItem'



components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Joe Doe:
          id: 1
          email: joe.doe@example.com
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          minimum: 1
          readOnly: true
        email:
          type: string
          format: email
      required:
        - id
        - email
    CatalogItem:
      title: Catalog Item
      type: object
      description: ''
      x-examples:
        Foo Item:
          id: fcb5d0b3-5fd9-45ef-a002-57fecfdc5dd0
          name: foo stuff
      properties:
        id:
          type: string
          description: Unique identifier for the given catalog item.
          readOnly: true
        name:
          type: string
      required:
        - id
        - name
