lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600


when@dev:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/dev/private.pem'
        public_key: '%kernel.project_dir%/config/jwt/dev/public.pem'


when@test:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/test/private.pem'
        public_key: '%kernel.project_dir%/config/jwt/test/public.pem'
