controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

iam_api_controllers:
  resource: ../../_iam/src/Adapter/Api/
  type: annotation

basket_api_controllers:
  resource: ../../_basket/src/Adapter/Api/
  type: annotation

catalog_api_controllers:
  resource: ../../_catalog/src/Adapter/Api/
  type: annotation